### ISSUE TITLE
Cannot delete Shared Notebook notes

### ISSUE THREAD

**Issue by GastroGeek** [HappenApps/Quiver#1209]
I just updated Quiver to the App store's v3.2.1 release and upon opening it I cannot delete any notes from my shared notebook(s). All other functionality seems OK (create new, sort, copy, export/import) but no matter what - nothing can be deleted. Latest macOS with updates...

I've rolled back to v3.1.3 for now... thanks for the hard work @ylian 👍

**Comment by ylian** [comment]
Thanks for reporting the issue. I can reproduce it. You can still drag the note to Trash. Just cmd+backspace doesn't work. Will fix in the next update. And this only happens in a shared notebook.

**Comment by GastroGeek** [comment]
Yes, I too only saw it happening in shared notebooks...

Great stuff, thanks for letting me know! This should suffice for now 😄

**Comment by ylian** [comment]
Fixed in 3.2.2.

**Comment by jloropez** [comment]
I have 3.2.7 for the Mac and it still shows the bug. I tried moving a note to the trash and got the following

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	0x00007fff6e856399 swift::metadataimpl::ValueWitnesses<swift::metadataimpl::ObjCRetainableBox>::initializeWithCopy(swift::OpaqueValue*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*) + 9
1   com.happenapps.Quiver         	0x00000001078b6c81 0x107824000 + 601217
2   com.happenapps.Quiver         	0x00000001078b703f 0x107824000 + 602175
3   com.happenapps.Quiver         	0x000000010784a46e 0x107824000 + 156782
4   com.happenapps.Quiver         	0x000000010782c0c1 0x107824000 + 32961
5   com.happenapps.Quiver         	0x000000010782c080 0x107824000 + 32896
6   com.apple.AppKit              	0x00007fff324af437 -[NSApplication(NSResponder) sendAction:to:from:] + 299
7   com.apple.AppKit              	0x00007fff324af2d2 -[NSControl sendAction:to:] + 86
8   com.apple.AppKit              	0x00007fff324af204 __26-[NSCell _sendActionFrom:]_block_invoke + 136
9   com.apple.AppKit              	0x00007fff324af106 -[NSCell _sendActionFrom:] + 171
10  com.apple.AppKit              	0x00007fff324af04d -[NSButtonCell _sendActionFrom:] + 96
11  com.apple.AppKit              	0x00007fff324ab32b NSControlTrackMouse + 1745
12  com.apple.AppKit              	0x00007fff324aac32 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 130
13  com.apple.AppKit              	0x00007fff324aaaf1 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 691
14  com.apple.AppKit              	0x00007fff324a9e6d -[NSControl mouseDown:] + 748
15  com.apple.AppKit              	0x00007fff324a8280 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4914
16  com.apple.AppKit              	0x00007fff32412a81 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
17  com.apple.AppKit              	0x00007fff32411e29 -[NSWindow(NSEventRouting) sendEvent:] + 349
18  com.apple.AppKit              	0x00007fff324101b4 -[NSApplication(NSEvent) sendEvent:] + 352
19  com.happenapps.Quiver         	0x000000010787e315 0x107824000 + 369429
20  com.apple.AppKit              	0x00007fff3225d21f -[NSApplication run] + 707
21  com.apple.AppKit              	0x00007fff3222eff6 NSApplicationMain + 777
22  libdyld.dylib                 	0x00007fff6ef36cc9 start + 1

Thread 1:
