### ISSUE TITLE
Notebooks have been deleted

### ISSUE THREAD

**Issue by ChristieRenaud** [HappenApps/Quiver#1337]
I opened Quiver today and my notebooks for the past year have vanished. I have daily work for three years and the last year is just gone. I have no idea what to do. I have tried opening the library from the ~/Library folder and nothing. A years worth of work is just gone. Please help.

**Comment by ylian** [comment]
Your notes should still be there. Please send some screenshots and detailed info (library location, notebook location) to me (ylian@happenapps.com), and I will help you from there.

**Comment by mkonia** [comment]
The same happened to me. Most of the entries vanished except the title of the entries!

**Comment by ylian** [comment]
Try to locate your Quiver library. When you find it, simply double click on it to open. That should resolve the issue.

**Comment by ylian** [comment]
Also, make sure to update to the latest version (3.2.6).

**Comment by mkonia** [comment]
Hi,

Thanks a lot for your immediate answer. Unfortunately, double clicking on the library does not resolve the issue. Quiver, version 3.2.6 (200)

Cheers
Mike

**Comment by ylian** [comment]
@mkonia That's weird. Please send me some screenshots. You can either post them here or send to ylian@happenapps.com for privacy.

**Comment by mkonia** [comment]
<img width="1191" alt="screenshot_01" src="https://user-images.githubusercontent.com/15304151/61153990-3383f080-a4ed-11e9-8039-d329781719d2.png">

**Comment by mkonia** [comment]
one of the rare entry that still works:
<img width="1191" alt="screenshot_02" src="https://user-images.githubusercontent.com/15304151/61154184-b6a54680-a4ed-11e9-92df-b44201d644e2.png">

**Comment by ylian** [comment]
@mkonia Thanks. Can you check Preferences > Sync > Library location, and then in Finder, check if that library exists, and its size. If you don't have any personal data in your notes, please zip the library and send to me, so I can check if the note files are okay.

**Comment by mkonia** [comment]
Finally, I could find the culprit: it’s the the new version of Dropbox (my Quiver library is hosted on Dropbox) that also causes a lot of problems with other apps. The issue could be solved by simply launching the Dropbox app.

Thanks again for your immediate reaction. Very much appreciated!

Cheers
Mike

**Comment by ylian** [comment]
@mkonia Thanks a lot for figuring out the issue. This info is quite useful to me, possibly other users as well.

**Comment by carlhung** [comment]
I have the same problem.
I removed dropbox.
but i still can't fix it.
anyway to reset Quiver's meta data?

**Comment by carlhung** [comment]
I reinstall Quiver and import the library.
it works now.
but can I use dropbox to backup the library?

**Comment by ylian** [comment]
@carlhung To back up your Quiver library, just make a copy of the Quiver.qvlibrary file. (The current library location can be found by File Menu > Show Library in Finder).

**Comment by timgluz** [comment]
Hi,

I have similar problem - when i open the Quiver-app, then it just shows note's header, but the content is empty; 
Current fix is to restore notebooks from Backup, but i have to do it every time i open the Quiver;

I see that version `3.2.5` tackled this issue, but seems it is not totally working in `3.2.6`

**Comment by ylian** [comment]
@timgluz I would need to know more about your setup (library location, etc.) in order to know why it's not working for you. Please send the detailed info to ylian@happenapps.com.
