### ISSUE TITLE
Constantly seeing 'changed on disk' dialogue

### ISSUE THREAD

**Issue by danielecook** [HappenApps/Quiver#283]
I am getting the "The Note "xxx" has been changed on disk" dialogue repeatedly using the app store version 3.0 of quiver. I am unable to add anything without seeing the dialogue.

Reloading from from disk or keep my changes results in the same outcome - that no changes to the note are made.

**Comment by ylian** [comment]
That shouldn't happen. What's your setup? How many computers syncing via which cloud service?

**Comment by JMichaelTX** [comment]
I'm seeing the same behavior, once or twice a day.
I have two Macs sync'd via Dropbox, but when this happens the other Mac been shutdown for at least an hour, usually much more.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/11052885/11603763/4b2d50a6-9aaa-11e5-8023-546bc8080d66.png)

**Comment by ylian** [comment]
@JMichaelTX Thanks. I will do two things:
1. I will add a check in the file change event handler, to check file content and only show this if the file content _actually_ changed.
2. The file change event obviously was triggered by something. It must have to do with a certain action. If this happens again, please take note of the action immediately preceding this, and that can help me find the bug.

**Comment by danielecook** [comment]
I'll be honest we have a good 12-14 computers syncing on he same Dropbox...

**Comment by ylian** [comment]
@danielecook Thanks. It's fine to have any number of syncing clients. I'm just trying to hunt down the bug. If this happens again, please note down the action right before this happens. That will help me. Thanks.

**Comment by dkarter** [comment]
I've encountered the same issue multiple times.

Here are my reproduction steps:
1. Quiver file is in Dropbox
2. Create a new note. (using the keyboard shortcut)
3. Write some stuff in the note and hit Cmd-s (muscle memory - I know it's not required)

**Expected**: I can close the note and get back to what I was doing.
**Actual**: The main window pops open and shows me the note I just created has changed on disk.

Note I am not syncing with any other computers, just have it in dropbox for backup purposes.
![image](https://cloud.githubusercontent.com/assets/551858/12081486/10f6ba5a-b240-11e5-88fe-728f043baa38.png)

**Comment by dkarter** [comment]
This is still an issue with 3.0.1. I'm getting those quite frequently. I think it's happening because I am typing my notes in a new window while the main window is open in the background.

Can happen if waiting a few seconds after completing the note and trying to change tags.

**Comment by ylian** [comment]
@dkarter Thanks. Will fix in 3.0.2. In the meantime, restarting the app might help.

**Comment by JMichaelTX** [comment]
> This is still an issue with 3.0.1. I'm getting those quite frequently

Same here.

**Comment by ylian** [comment]
@JMichaelTX Understood. I will make sure this is fixed in 3.0.2.

**Comment by Bouke** [comment]
This is still happening for me if my co-worker changes a file which I'm looking at. I didn't make any changes to the file and on every sync by dropbox the dreaded dialog shows up and the dock icon will start dancing. When the dialog isn't dismissed, e.g. when Quiver is in the background, any additional changes will even play a "plunk" alert sound to notify that an additional dialog couldn't be displayed. I'm on 3.1.1.

**Comment by 631068264** [comment]
It also happen in ver 3.1.2. Perhaps  it was related to the Cloud service because I change the cloud from Google Drive to BaiduYun in China. The issue didn't happen when use Google Drive.

![image](https://user-images.githubusercontent.com/8144089/36543230-201ef57e-181e-11e8-9d02-22c4afa76b7a.png)

**Comment by ylian** [comment]
Fixed in 3.2.1. Quiver now automatically reloads opened notes to the latest version.
