### ISSUE TITLE
Open files in Finder

### ISSUE THREAD

**Issue by rbtsv** [HappenApps/Quiver#88]
I have tried to open links to my files in the system like

``` markdown
[Link](file:///Users/rubtsov/testfile.html)
```

But Finder says that Quiver doesn't have the permission to open this file. Of course I've set all permissions before asking. For me this option is essential and I would be grateful if you fix it.

**Comment by ylian** [comment]
I see. You need to drag the file in to create the file link. Since Quiver is released on the Mac AppStore, it must be sandboxed. A sandboxed app doesn't have permission to the file system except for files or directories a user has opened using the file open panel, or dragged in.

**Comment by rbtsv** [comment]
There is a problem with dragging: links on files don't work after restart. But i have found the solution: it is enough to drag the folder, that contain all the files at any level (in my case it is the Dropbox folder) and everything works fine. Thank you very much! But, as I understand, there should be the way to let Quiver to remember a file or a folder after only one drag. It would be nice if it would be done.

**Comment by ylian** [comment]
Good catch. This can be fixed quite easily.

**Comment by ylian** [comment]
Fixed in 2.2b27.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b27.zip

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.

**Comment by iamaziz** [comment]
Hi, I still have the same problem :( and dragging doesn't work after after restarting Quiver.
I am running Quiver v3.0.3. Any ideas ?

**Comment by rbtsv** [comment]
Just tried it. The problem is still relevant, so as my solution. If you drag some folder that contain all your links, all the links will work.

**Comment by iamaziz** [comment]
You mean the links would still open even after you quit quiver? I tried dragging a folder, it would work as long as the app is running. But when I close the app then open it again all linked folders/files become inaccessible again (including the top folder) due to the permission problem. 

    The application “Quiver” does not have permission to open “Dropbox.”

**Comment by rbtsv** [comment]
I mean that if you drag a folder after each start of Quiver you will repair broken links.  But of course it is a problem that should be solved by the developers.

**Comment by iamaziz** [comment]
Oh, that's not so cool. I hope it could be fixed.

**Comment by tflo** [comment]
Permissions are still lost after restarting Quiver.

Quiver 3.1.1 (App Store); macOS 10.13

– Tom
